### ISSUE TITLE
Feature: Support multiple tables

### ISSUE THREAD

**Issue by dudleycarr** [ConduitIO/conduit-connector-postgres#23]
### Feature description

It would be great if the connector exposed the support for more than one table at a time. At the moment, the number of tables dictates the number of replication slots which is not ideal.

**Comment by dylanlott** [comment]
Hello and thank you for the feature request! We're currently exploring how we could handle this. I've opened a [discussion](https://github.com/ConduitIO/conduit/discussions/382) to go over some of the details for this. Let us know if you have additional feedback for your specific use case.
