### ISSUE TITLE
Bug: Last N messages always redelivered on reconnect

### ISSUE THREAD

**Issue by dudleycarr** [ConduitIO/conduit-connector-postgres#24]
### Bug description

A `Source` will redeliver a previously ACKed message on reconnect. 

The connector uses the LSN at the Position and passes that when ACKing a message. This seems to differ from the example provided in `jackc/pglogrepl` where the ACKed LSN is the offset from the `WALStart` to the end of the message:
https://github.com/jackc/pglogrepl/blob/master/example/pglogrepl_demo/main.go#L112

### Steps to reproduce

1. Create a publication
2. Create a non-temporary slot
3. Insert a value into the tracked table
4. Consume slot using `Source`
5. Kill the app after enough time has passed to ACK message.
6. Restart the app to consume slot using `Source`

Sample app to consume `Source`:
```go
package main

import (
	"context"
	"encoding/json"
	"os"

	"github.com/conduitio/conduit-connector-postgres/source"
)

func main() {
	ctx := context.Background()

	sourceConfig := map[string]string{
		"url":                     os.Getenv("DB_URL"),
		"table":                   os.Getenv("DB_TABLE"),
		"key":                     os.Getenv("DB_TABLE_KEY"),
		"columns":                 "",
		"snapshot_mode":           "never",
		"cdc_mode":                "logrepl",
		"logrepl.publicationName": os.Getenv("DB_PUBLICATION"),
		"logrepl.slotName":        os.Getenv("DB_SLOT_NAME"),
	}
	s := source.NewSource()
	if err := s.Configure(ctx, sourceConfig); err != nil {
		panic(err)
	}
	if err := s.Open(ctx, nil); err != nil {
		panic(err)
	}
	defer s.Teardown(ctx)

	for {
		record, err := s.Read(ctx)
		if err != nil {
			panic(err)
		}
		msg, err := json.Marshal(record.Payload)
		if err != nil {
			panic(err)
		}
		if err := s.Ack(ctx, record.Position); err != nil {
			panic(err)
		}

		println(string(msg))
	}
}
```

### Version

53d5c54

**Comment by lovromazgon** [comment]
Hi @dudleycarr!

Even though your example produces the result you describe, there is a misunderstanding about how and why positions are handled as they are. The connector assumes it is running as part of [Conduit](https://github.com/conduitio/conduit) and it is the responsibility of Conduit to store the last position of the connector. The second parameter to [`Open`](https://github.com/ConduitIO/conduit-connector-postgres/blob/53d5c54dd4bda6b9e262875700159abddf363690/source/source.go#L53) is an `sdk.Position` which is supplied by Conduit and contains the LSN, telling the connector where it left off and where it should ideally resume from if possible.

So to come back to your example, to make it work properly we would need to store the position somewhere and pass it to the connector when it starts (like Conduit does), for example like this:

```diff
package main

import (
	"context"
	"encoding/json"
	"os"

	"github.com/conduitio/conduit-connector-postgres/source"
+	sdk "github.com/conduitio/conduit-connector-sdk"
)

func main() {
	ctx := context.Background()

	sourceConfig := map[string]string{
		"url":                     os.Getenv("DB_URL"),
		"table":                   os.Getenv("DB_TABLE"),
		"key":                     os.Getenv("DB_TABLE_KEY"),
		"columns":                 "",
		"snapshot_mode":           "never",
		"cdc_mode":                "logrepl",
		"logrepl.publicationName": os.Getenv("DB_PUBLICATION"),
		"logrepl.slotName":        os.Getenv("DB_SLOT_NAME"),
	}
	s := source.NewSource()
	if err := s.Configure(ctx, sourceConfig); err != nil {
		panic(err)
	}
+	positionFile := "last-position.txt"
+	lastPosition, err := fetchLastPosition(positionFile)
+	if err != nil {
+		panic(err)
+	}
+	println("starting from", string(lastPosition))
-	if err := s.Open(ctx, nil); err != nil {
+	if err := s.Open(ctx, lastPosition); err != nil {
		panic(err)
	}
	defer s.Teardown(ctx)

	for {
		record, err := s.Read(ctx)
		if err != nil {
			panic(err)
		}
		msg, err := json.Marshal(record.Payload)
		if err != nil {
			panic(err)
		}
		if err := s.Ack(ctx, record.Position); err != nil {
			panic(err)
		}
+		if err := os.WriteFile(positionFile, record.Position, 0666); err != nil {
+			panic(err)
+		}

		println(string(msg))
	}
}
+
+func fetchLastPosition(path string) (sdk.Position, error) {
+	positionFileBytes, err := os.ReadFile(path)
+	if err != nil && !os.IsNotExist(err) {
+		return nil, err
+	}
+	return positionFileBytes, nil
+}
```

I hope this answers your question!

**Comment by dudleycarr** [comment]
Thanks for the reply. I'm hoping to use the Postgres connector in a context outside of conduit and not need to store the last position since Postgres replication doesn't require it (as far as I can tell).

I think it's still a bug in the handling of the replication connection, but it makes sense that it's a non-issue for conduit. Feel free to close the issue if you like.

**Comment by lovromazgon** [comment]
As you said, this is a non-issue for the use case we are targeting so I will close the issue. That said, we are happy to review and merge any PRs coming our way, so feel free to contribute!
